apiVersion: v1
kind: Service
metadata:
  name: api-server
  namespace: istio-test
  labels:
    app: api-server
spec:
  ports:
    - port: 8090
  selector:
    app: api-server
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  namespace: istio-test
  labels:
    app: api-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
        - name: api-server
          image: api-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8090