server:
  port: 8080

spring:
  application:
    name: api-client
  cloud:
    loadbalancer:
      enabled: true
      cache:
        enabled: false

feign:
  circuitbreaker:
    enabled: false
  oauth2:
    load-balanced: false

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
        exclude: info,env,metrics,httptrace,threaddump,heapdump

