server:
  port: 8080

spring:
  application:
    name: api-client
  cloud:
    loadbalancer:
      enabled: true
      cache:
        enabled: false

feign:
  circuitbreaker:
    enabled: false
  oauth2:
    load-balanced: false
